// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "add_buddy_t.h"

static int __add_buddy_t_hash_computed;
static uint64_t __add_buddy_t_hash;

uint64_t __add_buddy_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __add_buddy_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__add_buddy_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x6fcc050df82c6a63LL
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __add_buddy_t_get_hash(void)
{
    if (!__add_buddy_t_hash_computed) {
        __add_buddy_t_hash = (int64_t)__add_buddy_t_hash_recursive(NULL);
        __add_buddy_t_hash_computed = 1;
    }

    return __add_buddy_t_hash;
}

int __add_buddy_t_encode_array(void *buf, int offset, int maxlen, const add_buddy_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].my_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].buddy_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int add_buddy_t_encode(void *buf, int offset, int maxlen, const add_buddy_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __add_buddy_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __add_buddy_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __add_buddy_t_encoded_array_size(const add_buddy_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_t_encoded_array_size(&(p[element].my_id), 1);

        size += __int32_t_encoded_array_size(&(p[element].buddy_id), 1);

    }
    return size;
}

int add_buddy_t_encoded_size(const add_buddy_t *p)
{
    return 8 + __add_buddy_t_encoded_array_size(p, 1);
}

int __add_buddy_t_decode_array(const void *buf, int offset, int maxlen, add_buddy_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].my_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].buddy_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __add_buddy_t_decode_array_cleanup(add_buddy_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_decode_array_cleanup(&(p[element].my_id), 1);

        __int32_t_decode_array_cleanup(&(p[element].buddy_id), 1);

    }
    return 0;
}

int add_buddy_t_decode(const void *buf, int offset, int maxlen, add_buddy_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __add_buddy_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __add_buddy_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int add_buddy_t_decode_cleanup(add_buddy_t *p)
{
    return __add_buddy_t_decode_array_cleanup(p, 1);
}

int __add_buddy_t_clone_array(const add_buddy_t *p, add_buddy_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_clone_array(&(p[element].my_id), &(q[element].my_id), 1);

        __int32_t_clone_array(&(p[element].buddy_id), &(q[element].buddy_id), 1);

    }
    return 0;
}

add_buddy_t *add_buddy_t_copy(const add_buddy_t *p)
{
    add_buddy_t *q = (add_buddy_t*) malloc(sizeof(add_buddy_t));
    __add_buddy_t_clone_array(p, q, 1);
    return q;
}

void add_buddy_t_destroy(add_buddy_t *p)
{
    __add_buddy_t_decode_array_cleanup(p, 1);
    free(p);
}

