// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _add_buddy_t_h
#define _add_buddy_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define ADD_BUDDY_T_MSG_ID 6

typedef struct _add_buddy_t add_buddy_t;
struct _add_buddy_t
{
    int32_t    my_id;
    int32_t    buddy_id;
};

/**
 * Create a deep copy of a add_buddy_t.
 * When no longer needed, destroy it with add_buddy_t_destroy()
 */
add_buddy_t* add_buddy_t_copy(const add_buddy_t* to_copy);

/**
 * Destroy an instance of add_buddy_t created by add_buddy_t_copy()
 */
void add_buddy_t_destroy(add_buddy_t* to_destroy);

/**
 * Encode a message of type add_buddy_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to add_buddy_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int add_buddy_t_encode(void *buf, int offset, int maxlen, const add_buddy_t *p);

/**
 * Decode a message of type add_buddy_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with add_buddy_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int add_buddy_t_decode(const void *buf, int offset, int maxlen, add_buddy_t *msg);

/**
 * Release resources allocated by add_buddy_t_decode()
 * @return 0
 */
int add_buddy_t_decode_cleanup(add_buddy_t *p);

/**
 * Check how many bytes are required to encode a message of type add_buddy_t
 */
int add_buddy_t_encoded_size(const add_buddy_t *p);

// LCM support functions. Users should not call these
int64_t __add_buddy_t_get_hash(void);
uint64_t __add_buddy_t_hash_recursive(const __lcm_hash_ptr *p);
int     __add_buddy_t_encode_array(void *buf, int offset, int maxlen, const add_buddy_t *p, int elements);
int     __add_buddy_t_decode_array(const void *buf, int offset, int maxlen, add_buddy_t *p, int elements);
int     __add_buddy_t_decode_array_cleanup(add_buddy_t *p, int elements);
int     __add_buddy_t_encoded_array_size(const add_buddy_t *p, int elements);
int     __add_buddy_t_clone_array(const add_buddy_t *p, add_buddy_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
