// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "echo_request_t.h"

static int __echo_request_t_hash_computed;
static uint64_t __echo_request_t_hash;

uint64_t __echo_request_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __echo_request_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__echo_request_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x18f1ed839291afecLL
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __echo_request_t_get_hash(void)
{
    if (!__echo_request_t_hash_computed) {
        __echo_request_t_hash = (int64_t)__echo_request_t_hash_recursive(NULL);
        __echo_request_t_hash_computed = 1;
    }

    return __echo_request_t_hash;
}

int __echo_request_t_encode_array(void *buf, int offset, int maxlen, const echo_request_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].source_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].destination_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int echo_request_t_encode(void *buf, int offset, int maxlen, const echo_request_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __echo_request_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __echo_request_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __echo_request_t_encoded_array_size(const echo_request_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].source_id), 1);

        size += __int16_t_encoded_array_size(&(p[element].destination_id), 1);

    }
    return size;
}

int echo_request_t_encoded_size(const echo_request_t *p)
{
    return 8 + __echo_request_t_encoded_array_size(p, 1);
}

int __echo_request_t_decode_array(const void *buf, int offset, int maxlen, echo_request_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].source_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].destination_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __echo_request_t_decode_array_cleanup(echo_request_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].source_id), 1);

        __int16_t_decode_array_cleanup(&(p[element].destination_id), 1);

    }
    return 0;
}

int echo_request_t_decode(const void *buf, int offset, int maxlen, echo_request_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __echo_request_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __echo_request_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int echo_request_t_decode_cleanup(echo_request_t *p)
{
    return __echo_request_t_decode_array_cleanup(p, 1);
}

int __echo_request_t_clone_array(const echo_request_t *p, echo_request_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].source_id), &(q[element].source_id), 1);

        __int16_t_clone_array(&(p[element].destination_id), &(q[element].destination_id), 1);

    }
    return 0;
}

echo_request_t *echo_request_t_copy(const echo_request_t *p)
{
    echo_request_t *q = (echo_request_t*) malloc(sizeof(echo_request_t));
    __echo_request_t_clone_array(p, q, 1);
    return q;
}

void echo_request_t_destroy(echo_request_t *p)
{
    __echo_request_t_decode_array_cleanup(p, 1);
    free(p);
}

