// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _echo_request_t_h
#define _echo_request_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define ECHO_REQUEST_T_MSG_ID 7

typedef struct _echo_request_t echo_request_t;
struct _echo_request_t
{
    int32_t    source_id;
    int32_t    destination_id;
};

/**
 * Create a deep copy of a echo_request_t.
 * When no longer needed, destroy it with echo_request_t_destroy()
 */
echo_request_t* echo_request_t_copy(const echo_request_t* to_copy);

/**
 * Destroy an instance of echo_request_t created by echo_request_t_copy()
 */
void echo_request_t_destroy(echo_request_t* to_destroy);

/**
 * Encode a message of type echo_request_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to echo_request_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int echo_request_t_encode(void *buf, int offset, int maxlen, const echo_request_t *p);

/**
 * Decode a message of type echo_request_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with echo_request_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int echo_request_t_decode(const void *buf, int offset, int maxlen, echo_request_t *msg);

/**
 * Release resources allocated by echo_request_t_decode()
 * @return 0
 */
int echo_request_t_decode_cleanup(echo_request_t *p);

/**
 * Check how many bytes are required to encode a message of type echo_request_t
 */
int echo_request_t_encoded_size(const echo_request_t *p);

// LCM support functions. Users should not call these
int64_t __echo_request_t_get_hash(void);
uint64_t __echo_request_t_hash_recursive(const __lcm_hash_ptr *p);
int     __echo_request_t_encode_array(void *buf, int offset, int maxlen, const echo_request_t *p, int elements);
int     __echo_request_t_decode_array(const void *buf, int offset, int maxlen, echo_request_t *p, int elements);
int     __echo_request_t_decode_array_cleanup(echo_request_t *p, int elements);
int     __echo_request_t_encoded_array_size(const echo_request_t *p, int elements);
int     __echo_request_t_clone_array(const echo_request_t *p, echo_request_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
