// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _echo_reply_t_h
#define _echo_reply_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define ECHO_REPLY_T_MSG_ID 9

typedef struct _echo_reply_t echo_reply_t;
struct _echo_reply_t
{
    int16_t    source_id;
    int16_t    destination_id;
};

/**
 * Create a deep copy of a echo_reply_t.
 * When no longer needed, destroy it with echo_reply_t_destroy()
 */
echo_reply_t* echo_reply_t_copy(const echo_reply_t* to_copy);

/**
 * Destroy an instance of echo_reply_t created by echo_reply_t_copy()
 */
void echo_reply_t_destroy(echo_reply_t* to_destroy);

/**
 * Encode a message of type echo_reply_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to echo_reply_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int echo_reply_t_encode(void *buf, int offset, int maxlen, const echo_reply_t *p);

/**
 * Decode a message of type echo_reply_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with echo_reply_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int echo_reply_t_decode(const void *buf, int offset, int maxlen, echo_reply_t *msg);

/**
 * Release resources allocated by echo_reply_t_decode()
 * @return 0
 */
int echo_reply_t_decode_cleanup(echo_reply_t *p);

/**
 * Check how many bytes are required to encode a message of type echo_reply_t
 */
int echo_reply_t_encoded_size(const echo_reply_t *p);

// LCM support functions. Users should not call these
int64_t __echo_reply_t_get_hash(void);
uint64_t __echo_reply_t_hash_recursive(const __lcm_hash_ptr *p);
int     __echo_reply_t_encode_array(void *buf, int offset, int maxlen, const echo_reply_t *p, int elements);
int     __echo_reply_t_decode_array(const void *buf, int offset, int maxlen, echo_reply_t *p, int elements);
int     __echo_reply_t_decode_array_cleanup(echo_reply_t *p, int elements);
int     __echo_reply_t_encoded_array_size(const echo_reply_t *p, int elements);
int     __echo_reply_t_clone_array(const echo_reply_t *p, echo_reply_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
