// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _my_constants_t_h
#define _my_constants_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define MY_CONSTANTS_T_MSG_ID_VOICE_DATA 1
#define MY_CONSTANTS_T_MSG_ID_I_AM 2
#define MY_CONSTANTS_T_MSG_ID_WHO_IS 3
#define MY_CONSTANTS_T_MSG_ID_WHO_IS_REPLY 4

typedef struct _my_constants_t my_constants_t;
struct _my_constants_t
{
};

/**
 * Create a deep copy of a my_constants_t.
 * When no longer needed, destroy it with my_constants_t_destroy()
 */
my_constants_t* my_constants_t_copy(const my_constants_t* to_copy);

/**
 * Destroy an instance of my_constants_t created by my_constants_t_copy()
 */
void my_constants_t_destroy(my_constants_t* to_destroy);

/**
 * Encode a message of type my_constants_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to my_constants_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int my_constants_t_encode(void *buf, int offset, int maxlen, const my_constants_t *p);

/**
 * Decode a message of type my_constants_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with my_constants_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int my_constants_t_decode(const void *buf, int offset, int maxlen, my_constants_t *msg);

/**
 * Release resources allocated by my_constants_t_decode()
 * @return 0
 */
int my_constants_t_decode_cleanup(my_constants_t *p);

/**
 * Check how many bytes are required to encode a message of type my_constants_t
 */
int my_constants_t_encoded_size(const my_constants_t *p);

// LCM support functions. Users should not call these
int64_t __my_constants_t_get_hash(void);
uint64_t __my_constants_t_hash_recursive(const __lcm_hash_ptr *p);
int     __my_constants_t_encode_array(void *buf, int offset, int maxlen, const my_constants_t *p, int elements);
int     __my_constants_t_decode_array(const void *buf, int offset, int maxlen, my_constants_t *p, int elements);
int     __my_constants_t_decode_array_cleanup(my_constants_t *p, int elements);
int     __my_constants_t_encoded_array_size(const my_constants_t *p, int elements);
int     __my_constants_t_clone_array(const my_constants_t *p, my_constants_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
