// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "my_constants_t.h"

static int __my_constants_t_hash_computed;
static uint64_t __my_constants_t_hash;

uint64_t __my_constants_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __my_constants_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__my_constants_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x0000000012345678LL
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __my_constants_t_get_hash(void)
{
    if (!__my_constants_t_hash_computed) {
        __my_constants_t_hash = (int64_t)__my_constants_t_hash_recursive(NULL);
        __my_constants_t_hash_computed = 1;
    }

    return __my_constants_t_hash;
}

int __my_constants_t_encode_array(void *buf, int offset, int maxlen, const my_constants_t *p, int elements)
{
    int pos = 0, element;

    for (element = 0; element < elements; element++) {

    }
    return pos;
}

int my_constants_t_encode(void *buf, int offset, int maxlen, const my_constants_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __my_constants_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __my_constants_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __my_constants_t_encoded_array_size(const my_constants_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

    }
    return size;
}

int my_constants_t_encoded_size(const my_constants_t *p)
{
    return 8 + __my_constants_t_encoded_array_size(p, 1);
}

int __my_constants_t_decode_array(const void *buf, int offset, int maxlen, my_constants_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

    }
    return pos;
}

int __my_constants_t_decode_array_cleanup(my_constants_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

    }
    return 0;
}

int my_constants_t_decode(const void *buf, int offset, int maxlen, my_constants_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __my_constants_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __my_constants_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int my_constants_t_decode_cleanup(my_constants_t *p)
{
    return __my_constants_t_decode_array_cleanup(p, 1);
}

int __my_constants_t_clone_array(const my_constants_t *p, my_constants_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

    }
    return 0;
}

my_constants_t *my_constants_t_copy(const my_constants_t *p)
{
    my_constants_t *q = (my_constants_t*) malloc(sizeof(my_constants_t));
    __my_constants_t_clone_array(p, q, 1);
    return q;
}

void my_constants_t_destroy(my_constants_t *p)
{
    __my_constants_t_decode_array_cleanup(p, 1);
    free(p);
}

