// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _voice_data_t_h
#define _voice_data_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _voice_data_t voice_data_t;
struct _voice_data_t
{
    int16_t    destination_id;
    int16_t    data_size;
    int8_t     data[512-4-4];
};

/**
 * Create a deep copy of a voice_data_t.
 * When no longer needed, destroy it with voice_data_t_destroy()
 */
voice_data_t* voice_data_t_copy(const voice_data_t* to_copy);

/**
 * Destroy an instance of voice_data_t created by voice_data_t_copy()
 */
void voice_data_t_destroy(voice_data_t* to_destroy);

/**
 * Encode a message of type voice_data_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to voice_data_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int voice_data_t_encode(void *buf, int offset, int maxlen, const voice_data_t *p);

/**
 * Decode a message of type voice_data_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with voice_data_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int voice_data_t_decode(const void *buf, int offset, int maxlen, voice_data_t *msg);

/**
 * Release resources allocated by voice_data_t_decode()
 * @return 0
 */
int voice_data_t_decode_cleanup(voice_data_t *p);

/**
 * Check how many bytes are required to encode a message of type voice_data_t
 */
int voice_data_t_encoded_size(const voice_data_t *p);

// LCM support functions. Users should not call these
int64_t __voice_data_t_get_hash(void);
uint64_t __voice_data_t_hash_recursive(const __lcm_hash_ptr *p);
int     __voice_data_t_encode_array(void *buf, int offset, int maxlen, const voice_data_t *p, int elements);
int     __voice_data_t_decode_array(const void *buf, int offset, int maxlen, voice_data_t *p, int elements);
int     __voice_data_t_decode_array_cleanup(voice_data_t *p, int elements);
int     __voice_data_t_encoded_array_size(const voice_data_t *p, int elements);
int     __voice_data_t_clone_array(const voice_data_t *p, voice_data_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
