// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "who_is_reply_t.h"

static int __who_is_reply_t_hash_computed;
static uint64_t __who_is_reply_t_hash;

uint64_t __who_is_reply_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __who_is_reply_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__who_is_reply_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x4a63db5ad5c6199aLL
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __who_is_reply_t_get_hash(void)
{
    if (!__who_is_reply_t_hash_computed) {
        __who_is_reply_t_hash = (int64_t)__who_is_reply_t_hash_recursive(NULL);
        __who_is_reply_t_hash_computed = 1;
    }

    return __who_is_reply_t_hash;
}

int __who_is_reply_t_encode_array(void *buf, int offset, int maxlen, const who_is_reply_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].name, 32);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int who_is_reply_t_encode(void *buf, int offset, int maxlen, const who_is_reply_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __who_is_reply_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __who_is_reply_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __who_is_reply_t_encoded_array_size(const who_is_reply_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_t_encoded_array_size(&(p[element].id), 1);

        size += __int8_t_encoded_array_size(p[element].name, 32);

    }
    return size;
}

int who_is_reply_t_encoded_size(const who_is_reply_t *p)
{
    return 8 + __who_is_reply_t_encoded_array_size(p, 1);
}

int __who_is_reply_t_decode_array(const void *buf, int offset, int maxlen, who_is_reply_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].name, 32);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __who_is_reply_t_decode_array_cleanup(who_is_reply_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_decode_array_cleanup(&(p[element].id), 1);

        __int8_t_decode_array_cleanup(p[element].name, 32);

    }
    return 0;
}

int who_is_reply_t_decode(const void *buf, int offset, int maxlen, who_is_reply_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __who_is_reply_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __who_is_reply_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int who_is_reply_t_decode_cleanup(who_is_reply_t *p)
{
    return __who_is_reply_t_decode_array_cleanup(p, 1);
}

int __who_is_reply_t_clone_array(const who_is_reply_t *p, who_is_reply_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_clone_array(&(p[element].id), &(q[element].id), 1);

        __int8_t_clone_array(p[element].name, q[element].name, 32);

    }
    return 0;
}

who_is_reply_t *who_is_reply_t_copy(const who_is_reply_t *p)
{
    who_is_reply_t *q = (who_is_reply_t*) malloc(sizeof(who_is_reply_t));
    __who_is_reply_t_clone_array(p, q, 1);
    return q;
}

void who_is_reply_t_destroy(who_is_reply_t *p)
{
    __who_is_reply_t_decode_array_cleanup(p, 1);
    free(p);
}

