"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class keep_alive_resp_t(object):
    __slots__ = ["redirect_addr", "dummy"]

    MSG_ID = 8

    def __init__(self):
        self.redirect_addr = 0
        self.dummy = 0

    def encode(self):
        buf = BytesIO()
        buf.write(keep_alive_resp_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.redirect_addr, self.dummy))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != keep_alive_resp_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return keep_alive_resp_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = keep_alive_resp_t()
        self.redirect_addr, self.dummy = struct.unpack(">ii", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if keep_alive_resp_t in parents: return 0
        tmphash = (0xb382198df03e264) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if keep_alive_resp_t._packed_fingerprint is None:
            keep_alive_resp_t._packed_fingerprint = struct.pack(">Q", keep_alive_resp_t._get_hash_recursive([]))
        return keep_alive_resp_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

