"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class retransmit_req_t(object):
    __slots__ = ["source_id", "destination_id", "seq_number"]

    MSG_ID = 4

    def __init__(self):
        self.source_id = 0
        self.destination_id = 0
        self.seq_number = 0

    def encode(self):
        buf = BytesIO()
        buf.write(retransmit_req_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iii", self.source_id, self.destination_id, self.seq_number))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != retransmit_req_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return retransmit_req_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = retransmit_req_t()
        self.source_id, self.destination_id, self.seq_number = struct.unpack(">iii", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if retransmit_req_t in parents: return 0
        tmphash = (0xb2d79fa50a3281f5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if retransmit_req_t._packed_fingerprint is None:
            retransmit_req_t._packed_fingerprint = struct.pack(">Q", retransmit_req_t._get_hash_recursive([]))
        return retransmit_req_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

