"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class set_buddy_ack_t(object):
    __slots__ = ["buddy_id", "dummy"]

    MSG_ID = 5

    def __init__(self):
        self.buddy_id = 0
        self.dummy = [ 0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(set_buddy_ack_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.buddy_id))
        buf.write(struct.pack('>4b', *self.dummy[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != set_buddy_ack_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return set_buddy_ack_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = set_buddy_ack_t()
        self.buddy_id = struct.unpack(">i", buf.read(4))[0]
        self.dummy = struct.unpack('>4b', buf.read(4))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if set_buddy_ack_t in parents: return 0
        tmphash = (0xe5643de5c3829081) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if set_buddy_ack_t._packed_fingerprint is None:
            set_buddy_ack_t._packed_fingerprint = struct.pack(">Q", set_buddy_ack_t._get_hash_recursive([]))
        return set_buddy_ack_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

