"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class add_buddy_t(object):
    __slots__ = ["my_id", "buddy_id"]

    MSG_ID = 6

    def __init__(self):
        self.my_id = 0
        self.buddy_id = 0

    def encode(self):
        buf = BytesIO()
        buf.write(add_buddy_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.my_id, self.buddy_id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != add_buddy_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return add_buddy_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = add_buddy_t()
        self.my_id, self.buddy_id = struct.unpack(">ii", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if add_buddy_t in parents: return 0
        tmphash = (0x6fcc050df82c6a63) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if add_buddy_t._packed_fingerprint is None:
            add_buddy_t._packed_fingerprint = struct.pack(">Q", add_buddy_t._get_hash_recursive([]))
        return add_buddy_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

