#This file is autogenerated. Do not edit.
messageNameTable = [
	"",
	"VOICE_DATA", #1
	"I_AM", #2
	"RETIRE", #3
	"RETRANSMIT_REQ", #4
	"SET_BUDDY_ACK", #5
	"SET_BUDDY", #6
	"KEEP_ALIVE", #7
	"KEEP_ALIVE_RESP", #8
	"COMM_START", #9
	"COMM_START_ACK", #10
	"COMM_STOP", #11
	"COMM_STOP_ACK", #12
	"RETRANSMIT", #13
]
