#This file is autogenerated. Do not edit.
messageNameTable = [
	"",
	"VOICE_DATA", #1
	"I_AM", #2
	"I_AM_REPLY", #3
	"WHO_IS", #4
	"WHO_IS_REPLY", #5
	"SET_BUDDY", #6
	"KEEP_ALIVE", #7
	"",
	"COMM_START", #9
	"COMM_START_ACK", #10
	"COMM_STOP", #11
	"COMM_STOP_ACK", #12
]
