// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "set_buddy_ack_t.h"

static int __set_buddy_ack_t_hash_computed;
static uint64_t __set_buddy_ack_t_hash;

uint64_t __set_buddy_ack_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __set_buddy_ack_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__set_buddy_ack_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xe5643de5c3829081LL
         + __int32_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __set_buddy_ack_t_get_hash(void)
{
    if (!__set_buddy_ack_t_hash_computed) {
        __set_buddy_ack_t_hash = (int64_t)__set_buddy_ack_t_hash_recursive(NULL);
        __set_buddy_ack_t_hash_computed = 1;
    }

    return __set_buddy_ack_t_hash;
}

int __set_buddy_ack_t_encode_array(void *buf, int offset, int maxlen, const set_buddy_ack_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].buddy_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, p[element].dummy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int set_buddy_ack_t_encode(void *buf, int offset, int maxlen, const set_buddy_ack_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __set_buddy_ack_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __set_buddy_ack_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __set_buddy_ack_t_encoded_array_size(const set_buddy_ack_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_t_encoded_array_size(&(p[element].buddy_id), 1);

        size += __int8_t_encoded_array_size(p[element].dummy, 4);

    }
    return size;
}

int set_buddy_ack_t_encoded_size(const set_buddy_ack_t *p)
{
    return 8 + __set_buddy_ack_t_encoded_array_size(p, 1);
}

int __set_buddy_ack_t_decode_array(const void *buf, int offset, int maxlen, set_buddy_ack_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].buddy_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, p[element].dummy, 4);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __set_buddy_ack_t_decode_array_cleanup(set_buddy_ack_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_decode_array_cleanup(&(p[element].buddy_id), 1);

        __int8_t_decode_array_cleanup(p[element].dummy, 4);

    }
    return 0;
}

int set_buddy_ack_t_decode(const void *buf, int offset, int maxlen, set_buddy_ack_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __set_buddy_ack_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __set_buddy_ack_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int set_buddy_ack_t_decode_cleanup(set_buddy_ack_t *p)
{
    return __set_buddy_ack_t_decode_array_cleanup(p, 1);
}

int __set_buddy_ack_t_clone_array(const set_buddy_ack_t *p, set_buddy_ack_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_clone_array(&(p[element].buddy_id), &(q[element].buddy_id), 1);

        __int8_t_clone_array(p[element].dummy, q[element].dummy, 4);

    }
    return 0;
}

set_buddy_ack_t *set_buddy_ack_t_copy(const set_buddy_ack_t *p)
{
    set_buddy_ack_t *q = (set_buddy_ack_t*) malloc(sizeof(set_buddy_ack_t));
    __set_buddy_ack_t_clone_array(p, q, 1);
    return q;
}

void set_buddy_ack_t_destroy(set_buddy_ack_t *p)
{
    __set_buddy_ack_t_decode_array_cleanup(p, 1);
    free(p);
}

